language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
# deploy:
#   provider: heroku
#   api_key:
#     secure: x+jYu2a0PodHfX8cCmEUFi0xyL78NpNr9imG/P3bbzO2TzuHkWvBt2aOZO8qZkpsxOBjdn7gNAXgT7wpAqbB5bOwaZaUOd5vmk8XmMpMIDVXyz9cHrSwa3CiyRAFmlUM8TK6BDoQYLLx/2jdjo68/05DMg2vCbxNKnPowmJACmG4IteQ1sT+rTyogC83ZLTbUEoHOtW0IaZH2yoF0bjvpOT1tG2AtOInd2Zs3PNqFW1v+pmGyDt4FAWHCVd04OKB2i9vxt3eZk6xAvq+mfjmbEBKZpQ89yHX3rgtr7VDEf9PK+26dZBX3py8JKpqw5O4MllhZTj53R6+yKWrZP3hq38iijvcToRLRrT0PP9pVdJyLBepjU6HjigF6LumqX4+NTGckJj9lGpTkEawDODqSMZfJOTPGPZZ5IszPf8vBEzmOz+ntWTL2Upwc8nkJnUNaQ4mjt69LDOTWIc6ImrYUyurzOOOGYsp3TNIjYVYys6H7jk1elCDqSOueTnjT4yI/AOYTz7+p0TyhCpk5/6jtN4l5gVfmi8Wx2Yi0tAWrd+/hdlTQr5k/uV2O3usm0jrLCFo2X5midmXK4SIpWm4dhvQnJhStyvtG61+wcJY8NNp9KMmGtRfsdUh4OcP8f6P4dEiX6bfbNXuo0AJxlT+deHxxSbtu1tLj84Z45xEbr0=
