language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cQB0frHOhcVweas9tYt1MNozAFwOvcV6ETz1OnyeGvdudoIpZdhZ5OXsQqHFrsTJ2PMRxSWbRJFrs/VDPJkOEZqxVlF2kPMFQOnPsQJ8dVZ0Dg70tYjivrtvF4oNIcx1TLUFlO58lDzQJtbewXvHX0H9RUKm0UqMU6qL4kETudRraqlNiRrUSfaAkycUNL7OCZPY+FK4JnNo/wtTKibX/+EbAcqear3A5jsHZ9N+CikfrhjMHTewU43pTStIfwb03allzbVWArz2IEP0Uxx80VOaqA0XmWxd/ZoE7cbaqX033blttKR0lzro1KKQM7rWlmUqfzIaBw4nYR1zcV1PqJ3VgxTYK+aiKRfOaHR0t9LlLmcSztb4lPF8M4n6K5yv6ol6cfa2PkE+HdYPyWEG8zRtJwRLI8O2PsZ5b7Fge7/XjNO5aDMFUUV2S3paKgJOHytxMkiRtc4MYJHMZ1aRq6lTo88f3zFvTruDCavi9Kv+J4AOFqE0s0uXRHBDrR5/goeVYj8OaEz1Evv/79J6BTaIRsks8kaKoYz498hAPI5eNYsARYvSr7gmg6ioa/akFwkhY7Bdo/5kBcI31pwJaPPIQAMiOwA6kin7F6SjLFX1z5NUA6E9cBnWPRLTiOSscrsjwsDxwTrMS4qG1ax4fvpb8aYrfmP5dKElgrK16vU=
